[2023-02-08T01:19:05.974+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: entsoe-energydata-backfill.extract_generation scheduled__2021-01-01T00:00:00+00:00 [queued]>
[2023-02-08T01:19:05.992+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: entsoe-energydata-backfill.extract_generation scheduled__2021-01-01T00:00:00+00:00 [queued]>
[2023-02-08T01:19:05.992+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-02-08T01:19:05.992+0000] {taskinstance.py:1284} INFO - Starting attempt 7 of 10
[2023-02-08T01:19:05.992+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-02-08T01:19:06.011+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): extract_generation> on 2021-01-01 00:00:00+00:00
[2023-02-08T01:19:06.022+0000] {standard_task_runner.py:55} INFO - Started process 2861 to run task
[2023-02-08T01:19:06.029+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'entsoe-energydata-backfill', 'extract_generation', 'scheduled__2021-01-01T00:00:00+00:00', '--job-id', '1105', '--raw', '--subdir', 'DAGS_FOLDER/ingestion_energydata_dag.py', '--cfg-path', '/tmp/tmpe1do3iml']
[2023-02-08T01:19:06.034+0000] {standard_task_runner.py:83} INFO - Job 1105: Subtask extract_generation
[2023-02-08T01:19:06.256+0000] {task_command.py:389} INFO - Running <TaskInstance: entsoe-energydata-backfill.extract_generation scheduled__2021-01-01T00:00:00+00:00 [running]> on host 4e853e3e6d16
[2023-02-08T01:19:06.418+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=rafzul
AIRFLOW_CTX_DAG_ID=entsoe-energydata-backfill
AIRFLOW_CTX_TASK_ID=extract_generation
AIRFLOW_CTX_EXECUTION_DATE=2021-01-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=7
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-01-01T00:00:00+00:00
[2023-02-08T01:19:06.419+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: ExtractRawData.extract_raw_data() got multiple values for argument 'metrics_label'
[2023-02-08T01:19:06.435+0000] {taskinstance.py:1322} INFO - Marking task as UP_FOR_RETRY. dag_id=entsoe-energydata-backfill, task_id=extract_generation, execution_date=20210101T000000, start_date=20230208T011905, end_date=20230208T011906
[2023-02-08T01:19:06.457+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 1105 for task extract_generation (ExtractRawData.extract_raw_data() got multiple values for argument 'metrics_label'; 2861)
[2023-02-08T01:19:06.491+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-02-08T01:19:06.550+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
