[2023-02-08T01:25:09.703+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: entsoe-energydata-backfill.extract_generation scheduled__2021-01-01T00:00:00+00:00 [queued]>
[2023-02-08T01:25:09.720+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: entsoe-energydata-backfill.extract_generation scheduled__2021-01-01T00:00:00+00:00 [queued]>
[2023-02-08T01:25:09.720+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-02-08T01:25:09.721+0000] {taskinstance.py:1284} INFO - Starting attempt 8 of 10
[2023-02-08T01:25:09.721+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-02-08T01:25:09.748+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): extract_generation> on 2021-01-01 00:00:00+00:00
[2023-02-08T01:25:09.762+0000] {standard_task_runner.py:55} INFO - Started process 3193 to run task
[2023-02-08T01:25:09.772+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'entsoe-energydata-backfill', 'extract_generation', 'scheduled__2021-01-01T00:00:00+00:00', '--job-id', '1106', '--raw', '--subdir', 'DAGS_FOLDER/ingestion_energydata_dag.py', '--cfg-path', '/tmp/tmpf26um0ub']
[2023-02-08T01:25:09.777+0000] {standard_task_runner.py:83} INFO - Job 1106: Subtask extract_generation
[2023-02-08T01:25:09.883+0000] {task_command.py:389} INFO - Running <TaskInstance: entsoe-energydata-backfill.extract_generation scheduled__2021-01-01T00:00:00+00:00 [running]> on host 4e853e3e6d16
[2023-02-08T01:25:09.976+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=rafzul
AIRFLOW_CTX_DAG_ID=entsoe-energydata-backfill
AIRFLOW_CTX_TASK_ID=extract_generation
AIRFLOW_CTX_EXECUTION_DATE=2021-01-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=8
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-01-01T00:00:00+00:00
[2023-02-08T01:25:09.977+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/plugins/scripts/extract_raw.py", line 95, in extract_raw_data
    entsoe_client = EntsoeRawClient(api_key=security_token)
NameError: name 'security_token' is not defined
[2023-02-08T01:25:09.999+0000] {taskinstance.py:1322} INFO - Marking task as UP_FOR_RETRY. dag_id=entsoe-energydata-backfill, task_id=extract_generation, execution_date=20210101T000000, start_date=20230208T012509, end_date=20230208T012509
[2023-02-08T01:25:10.017+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 1106 for task extract_generation (name 'security_token' is not defined; 3193)
[2023-02-08T01:25:10.075+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-02-08T01:25:10.147+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
