[2023-02-08T00:41:26.362+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: entsoe-energydata-backfill.extract_generation scheduled__2021-01-01T00:00:00+00:00 [queued]>
[2023-02-08T00:41:26.375+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: entsoe-energydata-backfill.extract_generation scheduled__2021-01-01T00:00:00+00:00 [queued]>
[2023-02-08T00:41:26.375+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-02-08T00:41:26.375+0000] {taskinstance.py:1284} INFO - Starting attempt 3 of 5
[2023-02-08T00:41:26.375+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-02-08T00:41:26.387+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): extract_generation> on 2021-01-01 00:00:00+00:00
[2023-02-08T00:41:26.394+0000] {standard_task_runner.py:55} INFO - Started process 576 to run task
[2023-02-08T00:41:26.398+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'entsoe-energydata-backfill', 'extract_generation', 'scheduled__2021-01-01T00:00:00+00:00', '--job-id', '1101', '--raw', '--subdir', 'DAGS_FOLDER/ingestion_energydata_dag.py', '--cfg-path', '/tmp/tmpwc4k0jvz']
[2023-02-08T00:41:26.400+0000] {standard_task_runner.py:83} INFO - Job 1101: Subtask extract_generation
[2023-02-08T00:41:26.461+0000] {task_command.py:389} INFO - Running <TaskInstance: entsoe-energydata-backfill.extract_generation scheduled__2021-01-01T00:00:00+00:00 [running]> on host 4e853e3e6d16
[2023-02-08T00:41:26.532+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=rafzul
AIRFLOW_CTX_DAG_ID=entsoe-energydata-backfill
AIRFLOW_CTX_TASK_ID=extract_generation
AIRFLOW_CTX_EXECUTION_DATE=2021-01-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-01-01T00:00:00+00:00
[2023-02-08T00:41:26.532+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: ExtractRawData.extract_raw_data() got multiple values for argument 'metrics_label'
[2023-02-08T00:41:26.560+0000] {taskinstance.py:1322} INFO - Marking task as UP_FOR_RETRY. dag_id=entsoe-energydata-backfill, task_id=extract_generation, execution_date=20210101T000000, start_date=20230208T004126, end_date=20230208T004126
[2023-02-08T00:41:26.574+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 1101 for task extract_generation (ExtractRawData.extract_raw_data() got multiple values for argument 'metrics_label'; 576)
[2023-02-08T00:41:26.610+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-02-08T00:41:26.632+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
