[2023-02-08T01:16:24.524+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: entsoe-energydata-backfill.extract_generation scheduled__2021-01-01T00:00:00+00:00 [queued]>
[2023-02-08T01:16:24.556+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: entsoe-energydata-backfill.extract_generation scheduled__2021-01-01T00:00:00+00:00 [queued]>
[2023-02-08T01:16:24.557+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-02-08T01:16:24.557+0000] {taskinstance.py:1284} INFO - Starting attempt 6 of 9
[2023-02-08T01:16:24.558+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-02-08T01:16:24.608+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): extract_generation> on 2021-01-01 00:00:00+00:00
[2023-02-08T01:16:24.628+0000] {standard_task_runner.py:55} INFO - Started process 2704 to run task
[2023-02-08T01:16:24.636+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'entsoe-energydata-backfill', 'extract_generation', 'scheduled__2021-01-01T00:00:00+00:00', '--job-id', '1104', '--raw', '--subdir', 'DAGS_FOLDER/ingestion_energydata_dag.py', '--cfg-path', '/tmp/tmpy6ocdddt']
[2023-02-08T01:16:24.642+0000] {standard_task_runner.py:83} INFO - Job 1104: Subtask extract_generation
[2023-02-08T01:16:24.787+0000] {task_command.py:389} INFO - Running <TaskInstance: entsoe-energydata-backfill.extract_generation scheduled__2021-01-01T00:00:00+00:00 [running]> on host 4e853e3e6d16
[2023-02-08T01:16:24.937+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=rafzul
AIRFLOW_CTX_DAG_ID=entsoe-energydata-backfill
AIRFLOW_CTX_TASK_ID=extract_generation
AIRFLOW_CTX_EXECUTION_DATE=2021-01-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=6
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-01-01T00:00:00+00:00
[2023-02-08T01:16:24.939+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: ExtractRawData.extract_raw_data() got multiple values for argument 'metrics_label'
[2023-02-08T01:16:24.957+0000] {taskinstance.py:1322} INFO - Marking task as UP_FOR_RETRY. dag_id=entsoe-energydata-backfill, task_id=extract_generation, execution_date=20210101T000000, start_date=20230208T011624, end_date=20230208T011624
[2023-02-08T01:16:24.981+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 1104 for task extract_generation (ExtractRawData.extract_raw_data() got multiple values for argument 'metrics_label'; 2704)
[2023-02-08T01:16:25.009+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-02-08T01:16:25.056+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
